language: go
# go:
#   - "1.8"
branches:
  only:
    - master

install:
  - pwd
  - wget https://github.com/gohugoio/hugo/releases/download/v0.51/hugo_0.51_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  # Use incremental build to make deployment faster
  - mkdir public
  - cd ./public
  - git init
  - git config user.name "n0b0dy"
  - git config user.email "n0b0dypku@gmail.com"
  - git remote add origin "https://$GITHUB_TOKEN@${GH_REF}"
  - git pull
  - cd ..
script:
  - hugo
after_script:
  - cd ./public
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push origin master
env:
 global:
   # Github Pages
   - GH_REF: github.com/n0b0dyCN/n0b0dyCN.github.io.git
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: public
  fqdn: n0b0dycn.me
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master